name: bp3m
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - astropy
  - astroquery
  - matplotlib
  - tqdm
  - pandas
  - joblib
  - jax
  - jaxlib
  - pip
  - pip:
    - bp3m
